/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminProtectionRouteImport } from './routes/admin.protection'
import { Route as AdminNamespacesRouteImport } from './routes/admin.namespaces'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminBlocklistsRouteImport } from './routes/admin.blocklists'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminApprovalQueueRouteImport } from './routes/admin.approval-queue'
import { Route as WikiSlugEditRouteImport } from './routes/wiki_.$slug.edit'
import { Route as WikiSlugHistoryRouteImport } from './routes/wiki.$slug.history'
import { Route as WikiSlugDiffRouteImport } from './routes/wiki.$slug.diff'
import { Route as WikiNamespaceSlugRouteImport } from './routes/wiki.$namespace.$slug'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as WikiNamespaceSlugEditRouteImport } from './routes/wiki_.$namespace.$slug.edit'
import { Route as WikiNamespaceSlugHistoryRouteImport } from './routes/wiki.$namespace.$slug.history'
import { Route as WikiNamespaceSlugDiffRouteImport } from './routes/wiki.$namespace.$slug.diff'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectionRoute = AdminProtectionRouteImport.update({
  id: '/admin/protection',
  path: '/admin/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNamespacesRoute = AdminNamespacesRouteImport.update({
  id: '/admin/namespaces',
  path: '/admin/namespaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlocklistsRoute = AdminBlocklistsRouteImport.update({
  id: '/admin/blocklists',
  path: '/admin/blocklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalQueueRoute = AdminApprovalQueueRouteImport.update({
  id: '/admin/approval-queue',
  path: '/admin/approval-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugEditRoute = WikiSlugEditRouteImport.update({
  id: '/wiki_/$slug/edit',
  path: '/wiki/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugHistoryRoute = WikiSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiSlugDiffRoute = WikiSlugDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiNamespaceSlugRoute = WikiNamespaceSlugRouteImport.update({
  id: '/wiki/$namespace/$slug',
  path: '/wiki/$namespace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const WikiNamespaceSlugEditRoute = WikiNamespaceSlugEditRouteImport.update({
  id: '/wiki_/$namespace/$slug/edit',
  path: '/wiki/$namespace/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiNamespaceSlugHistoryRoute =
  WikiNamespaceSlugHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => WikiNamespaceSlugRoute,
  } as any)
const WikiNamespaceSlugDiffRoute = WikiNamespaceSlugDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => WikiNamespaceSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/approval-queue': typeof AdminApprovalQueueRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/blocklists': typeof AdminBlocklistsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/namespaces': typeof AdminNamespacesRoute
  '/admin/protection': typeof AdminProtectionRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/wiki/$namespace/$slug': typeof WikiNamespaceSlugRouteWithChildren
  '/wiki/$slug/diff': typeof WikiSlugDiffRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$namespace/$slug/diff': typeof WikiNamespaceSlugDiffRoute
  '/wiki/$namespace/$slug/history': typeof WikiNamespaceSlugHistoryRoute
  '/wiki/$namespace/$slug/edit': typeof WikiNamespaceSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/approval-queue': typeof AdminApprovalQueueRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/blocklists': typeof AdminBlocklistsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/namespaces': typeof AdminNamespacesRoute
  '/admin/protection': typeof AdminProtectionRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/wiki/$namespace/$slug': typeof WikiNamespaceSlugRouteWithChildren
  '/wiki/$slug/diff': typeof WikiSlugDiffRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$namespace/$slug/diff': typeof WikiNamespaceSlugDiffRoute
  '/wiki/$namespace/$slug/history': typeof WikiNamespaceSlugHistoryRoute
  '/wiki/$namespace/$slug/edit': typeof WikiNamespaceSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/approval-queue': typeof AdminApprovalQueueRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/blocklists': typeof AdminBlocklistsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/namespaces': typeof AdminNamespacesRoute
  '/admin/protection': typeof AdminProtectionRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/wiki/$namespace/$slug': typeof WikiNamespaceSlugRouteWithChildren
  '/wiki/$slug/diff': typeof WikiSlugDiffRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki_/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$namespace/$slug/diff': typeof WikiNamespaceSlugDiffRoute
  '/wiki/$namespace/$slug/history': typeof WikiNamespaceSlugHistoryRoute
  '/wiki_/$namespace/$slug/edit': typeof WikiNamespaceSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/watchlist'
    | '/admin/approval-queue'
    | '/admin/audit-log'
    | '/admin/blocklists'
    | '/admin/config'
    | '/admin/namespaces'
    | '/admin/protection'
    | '/admin/roles'
    | '/admin/users'
    | '/category/$slug'
    | '/tag/$tag'
    | '/wiki/$slug'
    | '/admin/'
    | '/wiki/'
    | '/admin/users/$id'
    | '/wiki/$namespace/$slug'
    | '/wiki/$slug/diff'
    | '/wiki/$slug/history'
    | '/wiki/$slug/edit'
    | '/wiki/$namespace/$slug/diff'
    | '/wiki/$namespace/$slug/history'
    | '/wiki/$namespace/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/watchlist'
    | '/admin/approval-queue'
    | '/admin/audit-log'
    | '/admin/blocklists'
    | '/admin/config'
    | '/admin/namespaces'
    | '/admin/protection'
    | '/admin/roles'
    | '/admin/users'
    | '/category/$slug'
    | '/tag/$tag'
    | '/wiki/$slug'
    | '/admin'
    | '/wiki'
    | '/admin/users/$id'
    | '/wiki/$namespace/$slug'
    | '/wiki/$slug/diff'
    | '/wiki/$slug/history'
    | '/wiki/$slug/edit'
    | '/wiki/$namespace/$slug/diff'
    | '/wiki/$namespace/$slug/history'
    | '/wiki/$namespace/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/watchlist'
    | '/admin/approval-queue'
    | '/admin/audit-log'
    | '/admin/blocklists'
    | '/admin/config'
    | '/admin/namespaces'
    | '/admin/protection'
    | '/admin/roles'
    | '/admin/users'
    | '/category/$slug'
    | '/tag/$tag'
    | '/wiki/$slug'
    | '/admin/'
    | '/wiki/'
    | '/admin/users/$id'
    | '/wiki/$namespace/$slug'
    | '/wiki/$slug/diff'
    | '/wiki/$slug/history'
    | '/wiki_/$slug/edit'
    | '/wiki/$namespace/$slug/diff'
    | '/wiki/$namespace/$slug/history'
    | '/wiki_/$namespace/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  AdminApprovalQueueRoute: typeof AdminApprovalQueueRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBlocklistsRoute: typeof AdminBlocklistsRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminNamespacesRoute: typeof AdminNamespacesRoute
  AdminProtectionRoute: typeof AdminProtectionRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  TagTagRoute: typeof TagTagRoute
  WikiSlugRoute: typeof WikiSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  WikiNamespaceSlugRoute: typeof WikiNamespaceSlugRouteWithChildren
  WikiSlugEditRoute: typeof WikiSlugEditRoute
  WikiNamespaceSlugEditRoute: typeof WikiNamespaceSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/protection': {
      id: '/admin/protection'
      path: '/admin/protection'
      fullPath: '/admin/protection'
      preLoaderRoute: typeof AdminProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/namespaces': {
      id: '/admin/namespaces'
      path: '/admin/namespaces'
      fullPath: '/admin/namespaces'
      preLoaderRoute: typeof AdminNamespacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blocklists': {
      id: '/admin/blocklists'
      path: '/admin/blocklists'
      fullPath: '/admin/blocklists'
      preLoaderRoute: typeof AdminBlocklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approval-queue': {
      id: '/admin/approval-queue'
      path: '/admin/approval-queue'
      fullPath: '/admin/approval-queue'
      preLoaderRoute: typeof AdminApprovalQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki_/$slug/edit': {
      id: '/wiki_/$slug/edit'
      path: '/wiki/$slug/edit'
      fullPath: '/wiki/$slug/edit'
      preLoaderRoute: typeof WikiSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/history': {
      id: '/wiki/$slug/history'
      path: '/history'
      fullPath: '/wiki/$slug/history'
      preLoaderRoute: typeof WikiSlugHistoryRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$slug/diff': {
      id: '/wiki/$slug/diff'
      path: '/diff'
      fullPath: '/wiki/$slug/diff'
      preLoaderRoute: typeof WikiSlugDiffRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$namespace/$slug': {
      id: '/wiki/$namespace/$slug'
      path: '/wiki/$namespace/$slug'
      fullPath: '/wiki/$namespace/$slug'
      preLoaderRoute: typeof WikiNamespaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/wiki_/$namespace/$slug/edit': {
      id: '/wiki_/$namespace/$slug/edit'
      path: '/wiki/$namespace/$slug/edit'
      fullPath: '/wiki/$namespace/$slug/edit'
      preLoaderRoute: typeof WikiNamespaceSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$namespace/$slug/history': {
      id: '/wiki/$namespace/$slug/history'
      path: '/history'
      fullPath: '/wiki/$namespace/$slug/history'
      preLoaderRoute: typeof WikiNamespaceSlugHistoryRouteImport
      parentRoute: typeof WikiNamespaceSlugRoute
    }
    '/wiki/$namespace/$slug/diff': {
      id: '/wiki/$namespace/$slug/diff'
      path: '/diff'
      fullPath: '/wiki/$namespace/$slug/diff'
      preLoaderRoute: typeof WikiNamespaceSlugDiffRouteImport
      parentRoute: typeof WikiNamespaceSlugRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface WikiSlugRouteChildren {
  WikiSlugDiffRoute: typeof WikiSlugDiffRoute
  WikiSlugHistoryRoute: typeof WikiSlugHistoryRoute
}

const WikiSlugRouteChildren: WikiSlugRouteChildren = {
  WikiSlugDiffRoute: WikiSlugDiffRoute,
  WikiSlugHistoryRoute: WikiSlugHistoryRoute,
}

const WikiSlugRouteWithChildren = WikiSlugRoute._addFileChildren(
  WikiSlugRouteChildren,
)

interface WikiNamespaceSlugRouteChildren {
  WikiNamespaceSlugDiffRoute: typeof WikiNamespaceSlugDiffRoute
  WikiNamespaceSlugHistoryRoute: typeof WikiNamespaceSlugHistoryRoute
}

const WikiNamespaceSlugRouteChildren: WikiNamespaceSlugRouteChildren = {
  WikiNamespaceSlugDiffRoute: WikiNamespaceSlugDiffRoute,
  WikiNamespaceSlugHistoryRoute: WikiNamespaceSlugHistoryRoute,
}

const WikiNamespaceSlugRouteWithChildren =
  WikiNamespaceSlugRoute._addFileChildren(WikiNamespaceSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  AdminApprovalQueueRoute: AdminApprovalQueueRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBlocklistsRoute: AdminBlocklistsRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminNamespacesRoute: AdminNamespacesRoute,
  AdminProtectionRoute: AdminProtectionRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  TagTagRoute: TagTagRoute,
  WikiSlugRoute: WikiSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  WikiNamespaceSlugRoute: WikiNamespaceSlugRouteWithChildren,
  WikiSlugEditRoute: WikiSlugEditRoute,
  WikiNamespaceSlugEditRoute: WikiNamespaceSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
