/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as WikiSlugEditRouteImport } from './routes/wiki_.$slug.edit'
import { Route as WikiSlugHistoryRouteImport } from './routes/wiki.$slug.history'
import { Route as WikiSlugDiffRouteImport } from './routes/wiki.$slug.diff'
import { Route as WikiNamespaceSlugRouteImport } from './routes/wiki.$namespace.$slug'
import { Route as WikiNamespaceSlugEditRouteImport } from './routes/wiki_.$namespace.$slug.edit'
import { Route as WikiNamespaceSlugHistoryRouteImport } from './routes/wiki.$namespace.$slug.history'
import { Route as WikiNamespaceSlugDiffRouteImport } from './routes/wiki.$namespace.$slug.diff'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugEditRoute = WikiSlugEditRouteImport.update({
  id: '/wiki_/$slug/edit',
  path: '/wiki/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugHistoryRoute = WikiSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiSlugDiffRoute = WikiSlugDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiNamespaceSlugRoute = WikiNamespaceSlugRouteImport.update({
  id: '/wiki/$namespace/$slug',
  path: '/wiki/$namespace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiNamespaceSlugEditRoute = WikiNamespaceSlugEditRouteImport.update({
  id: '/wiki_/$namespace/$slug/edit',
  path: '/wiki/$namespace/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiNamespaceSlugHistoryRoute =
  WikiNamespaceSlugHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => WikiNamespaceSlugRoute,
  } as any)
const WikiNamespaceSlugDiffRoute = WikiNamespaceSlugDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => WikiNamespaceSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$namespace/$slug': typeof WikiNamespaceSlugRouteWithChildren
  '/wiki/$slug/diff': typeof WikiSlugDiffRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$namespace/$slug/diff': typeof WikiNamespaceSlugDiffRoute
  '/wiki/$namespace/$slug/history': typeof WikiNamespaceSlugHistoryRoute
  '/wiki/$namespace/$slug/edit': typeof WikiNamespaceSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki': typeof WikiIndexRoute
  '/wiki/$namespace/$slug': typeof WikiNamespaceSlugRouteWithChildren
  '/wiki/$slug/diff': typeof WikiSlugDiffRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$namespace/$slug/diff': typeof WikiNamespaceSlugDiffRoute
  '/wiki/$namespace/$slug/history': typeof WikiNamespaceSlugHistoryRoute
  '/wiki/$namespace/$slug/edit': typeof WikiNamespaceSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$namespace/$slug': typeof WikiNamespaceSlugRouteWithChildren
  '/wiki/$slug/diff': typeof WikiSlugDiffRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki_/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$namespace/$slug/diff': typeof WikiNamespaceSlugDiffRoute
  '/wiki/$namespace/$slug/history': typeof WikiNamespaceSlugHistoryRoute
  '/wiki_/$namespace/$slug/edit': typeof WikiNamespaceSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/search'
    | '/category/$slug'
    | '/tag/$tag'
    | '/wiki/$slug'
    | '/wiki/'
    | '/wiki/$namespace/$slug'
    | '/wiki/$slug/diff'
    | '/wiki/$slug/history'
    | '/wiki/$slug/edit'
    | '/wiki/$namespace/$slug/diff'
    | '/wiki/$namespace/$slug/history'
    | '/wiki/$namespace/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/category/$slug'
    | '/tag/$tag'
    | '/wiki/$slug'
    | '/wiki'
    | '/wiki/$namespace/$slug'
    | '/wiki/$slug/diff'
    | '/wiki/$slug/history'
    | '/wiki/$slug/edit'
    | '/wiki/$namespace/$slug/diff'
    | '/wiki/$namespace/$slug/history'
    | '/wiki/$namespace/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/search'
    | '/category/$slug'
    | '/tag/$tag'
    | '/wiki/$slug'
    | '/wiki/'
    | '/wiki/$namespace/$slug'
    | '/wiki/$slug/diff'
    | '/wiki/$slug/history'
    | '/wiki_/$slug/edit'
    | '/wiki/$namespace/$slug/diff'
    | '/wiki/$namespace/$slug/history'
    | '/wiki_/$namespace/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  TagTagRoute: typeof TagTagRoute
  WikiSlugRoute: typeof WikiSlugRouteWithChildren
  WikiIndexRoute: typeof WikiIndexRoute
  WikiNamespaceSlugRoute: typeof WikiNamespaceSlugRouteWithChildren
  WikiSlugEditRoute: typeof WikiSlugEditRoute
  WikiNamespaceSlugEditRoute: typeof WikiNamespaceSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki_/$slug/edit': {
      id: '/wiki_/$slug/edit'
      path: '/wiki/$slug/edit'
      fullPath: '/wiki/$slug/edit'
      preLoaderRoute: typeof WikiSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/history': {
      id: '/wiki/$slug/history'
      path: '/history'
      fullPath: '/wiki/$slug/history'
      preLoaderRoute: typeof WikiSlugHistoryRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$slug/diff': {
      id: '/wiki/$slug/diff'
      path: '/diff'
      fullPath: '/wiki/$slug/diff'
      preLoaderRoute: typeof WikiSlugDiffRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$namespace/$slug': {
      id: '/wiki/$namespace/$slug'
      path: '/wiki/$namespace/$slug'
      fullPath: '/wiki/$namespace/$slug'
      preLoaderRoute: typeof WikiNamespaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki_/$namespace/$slug/edit': {
      id: '/wiki_/$namespace/$slug/edit'
      path: '/wiki/$namespace/$slug/edit'
      fullPath: '/wiki/$namespace/$slug/edit'
      preLoaderRoute: typeof WikiNamespaceSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$namespace/$slug/history': {
      id: '/wiki/$namespace/$slug/history'
      path: '/history'
      fullPath: '/wiki/$namespace/$slug/history'
      preLoaderRoute: typeof WikiNamespaceSlugHistoryRouteImport
      parentRoute: typeof WikiNamespaceSlugRoute
    }
    '/wiki/$namespace/$slug/diff': {
      id: '/wiki/$namespace/$slug/diff'
      path: '/diff'
      fullPath: '/wiki/$namespace/$slug/diff'
      preLoaderRoute: typeof WikiNamespaceSlugDiffRouteImport
      parentRoute: typeof WikiNamespaceSlugRoute
    }
  }
}

interface WikiSlugRouteChildren {
  WikiSlugDiffRoute: typeof WikiSlugDiffRoute
  WikiSlugHistoryRoute: typeof WikiSlugHistoryRoute
}

const WikiSlugRouteChildren: WikiSlugRouteChildren = {
  WikiSlugDiffRoute: WikiSlugDiffRoute,
  WikiSlugHistoryRoute: WikiSlugHistoryRoute,
}

const WikiSlugRouteWithChildren = WikiSlugRoute._addFileChildren(
  WikiSlugRouteChildren,
)

interface WikiNamespaceSlugRouteChildren {
  WikiNamespaceSlugDiffRoute: typeof WikiNamespaceSlugDiffRoute
  WikiNamespaceSlugHistoryRoute: typeof WikiNamespaceSlugHistoryRoute
}

const WikiNamespaceSlugRouteChildren: WikiNamespaceSlugRouteChildren = {
  WikiNamespaceSlugDiffRoute: WikiNamespaceSlugDiffRoute,
  WikiNamespaceSlugHistoryRoute: WikiNamespaceSlugHistoryRoute,
}

const WikiNamespaceSlugRouteWithChildren =
  WikiNamespaceSlugRoute._addFileChildren(WikiNamespaceSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  TagTagRoute: TagTagRoute,
  WikiSlugRoute: WikiSlugRouteWithChildren,
  WikiIndexRoute: WikiIndexRoute,
  WikiNamespaceSlugRoute: WikiNamespaceSlugRouteWithChildren,
  WikiSlugEditRoute: WikiSlugEditRoute,
  WikiNamespaceSlugEditRoute: WikiNamespaceSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
